"""Create Project tables

Revision ID: 239cc99167b6
Revises: b6f70b972487
Create Date: 2025-12-21 23:36:40.835742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239cc99167b6'
down_revision = 'b6f70b972487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('proposed_solution', sa.Text(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'RECRUITING', 'ACTIVE', 'COMPLETED', 'REJECTED', name='projectstatus'), nullable=False),
    sa.Column('vote_score', sa.Integer(), nullable=True),
    sa.Column('proposal_deadline', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='unique_project_vote')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_votes')
    op.drop_table('projects')
    # ### end Alembic commands ###
