"""Create tables for poststs

Revision ID: 6f29ab2a73e7
Revises: 928e10bbe7e0
Create Date: 2025-12-20 02:08:23.675266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f29ab2a73e7'
down_revision = '928e10bbe7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
